### ISSUE TITLE
Erreur log serveur

### ISSUE THREAD

**Issue by cjeje84** [Novax69/ARMA3-LIFE-Lottery#1]
Bonjour je voudrais dejas vous remerciez du travail que vous faite c'est du bon travail merci encore

J'ai une erreur dans mes log serveur.

`Error in expression <Answer"];

_ticketAmmount = LIFE_SETTING(getNumber,"nov_loteryTicket");

_mode =>
11:15:01   Error position: <(getNumber,"nov_loteryTicket");

_mode =>
11:15:01   Error Missing ;
11:15:01 File NovScript\lotery\fn_NovLoteryMenu.sqf [life_fnc_NovLoteryMenu]..., line 74
11:15:01 Error in expression <Answer"];

_ticketAmmount = LIFE_SETTING(getNumber,"nov_loteryTicket");

_mode =>
11:15:01   Error position: <(getNumber,"nov_loteryTicket");

_mode =>
11:15:01   Error Missing ;
11:15:01 File NovScript\lotery\fn_NovLoteryMenu.sqf [life_fnc_NovLoteryMenu]..., line 74`

**Comment by Novax69** [comment]
Salut ! déjà merci du compliment ça fait plaisir :)

As-tu bien pensé à mettre les variables dans ton config_Master ? On dirait qu'il ne détecte pas les variables...

Si jamais hésite pas à me contacter sur discord : Damien / Novax#5158

**Comment by Novax69** [comment]
Petite correction, remplace le fichier NovScript/lotery/fn_NovLoteryMenu.sqf par la nouvelle version sur le github, j'ai fait une faute de frappes que je viens de remarqué ça devrais corriger le problème :)

**Comment by cjeje84** [comment]
Super ça fonctionne tu fait du trés beau boulot et je te remercie encore pour ton travail je t'es ajouter sur discord mes je ne peut pas t'envoyer de message si tu veux j'ai un teamspeak

**Comment by Novax69** [comment]
Nickel et merci encore :)
Je t'ai accepté sur discord ! 
Je clos l'issue merci d'avoir signalé ce bug :)
